name: 'Java Setup'
description: 'Installs Java'

runs:
  using: 'composite'
  steps:
    - name: Install Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'gradle'
